Problem: build-abi script enters failing state
- Avoid glob matches like "*.sol" when no files match.
- Watch directories for files being added and removed and re-run
  build-abi script if changes are detected

diff --git a/bin/build-abi-watch b/bin/build-abi-watch
--- a/bin/build-abi-watch
+++ b/bin/build-abi-watch
@@ -1,3 +1,11 @@
 #!/usr/bin/env bash
-set -e
-find contracts -iname "*.sol" | entr -c build-abi
+#
+# Entr exit code
+#  0       Normal termination after receiving SIGINT (Note: also Ctrl-C)
+#  1       No regular files were provided as input or an error occurred
+#  2       A file was added to a directory and the directory watch option was specified
+#
+while ! find contracts -iname "*.sol" | entr -d -c build-abi; do
+    sleep 0.1
+done
+echo "Ctrl-C detected, exiting ..."
